language: python
cache: apt
notifications:
  email: false

jobs:
  include:
  - python: 3.8
    name: "Website Build"
  - python: 3.8
    name: "Data Linting"

install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then pip install pelican==3.3 ghp-import markdown; fi

script:
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.8/dist-packages; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then make html; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then ./data/lint-list.py clients.json; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then ./data/lint-list.py servers.json; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then ./data/lint-list.py libraries.json; fi
